Test wheels on all kinds of linux distros

diff --git a/.github/workflows/pypi_publish.yml b/.github/workflows/pypi_publish.yml
--- a/.github/workflows/pypi_publish.yml
+++ b/.github/workflows/pypi_publish.yml
@@ -59,10 +59,108 @@ jobs:
         name: vmecpp-sdist
         path: ./wheelhouse/*.tar.gz
 
+  test-on-different-distros:
+    name: Test Linux distros
+    needs: main
+    strategy:
+      fail-fast: false
+      matrix:
+        distro:
+          [
+            "ubuntu:24.04",
+            "ubuntu:22.04",
+            "archlinux/archlinux",
+            "debian:12",
+            "debian:testing-20250224",
+            "fedora:41",
+          ]
+        test-mpi: [ true, false ]
+    runs-on: ubuntu-24.04
+    container: ${{ matrix.distro }}
+
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Install Python (Distro-Specific)
+        run: |
+          case ${{ matrix.distro }} in
+            ubuntu*|debian*)
+              apt update
+              apt install -y python3-venv
+              ;;
+            fedora*)
+              dnf -y update && dnf clean all
+              dnf -y install python-pip
+              ;;
+            archlinux*)
+              pacman -Sy --noconfirm python-pip
+              ;;
+            *)
+              echo "Unsupported distribution: ${{ matrix.distro }}"
+              exit 1
+              ;;
+          esac
+
+          python3 -m venv venv
+
+      - name: Install OpenMPI (Distro-Specific)
+        if: matrix.test-mpi
+        # mpi4py is a dependency of simsopt and needs a system-wide MPI installation to compile.
+        # This requires both a working OpenMPI installation and Python.h headers.
+        run: |
+          case ${{ matrix.distro }} in
+            ubuntu*|debian*)
+              apt install -y openmpi-bin libopenmpi-dev python3-dev
+              ;;
+            fedora*)
+              dnf install -y openmpi openmpi-devel python-devel
+              ;;
+            archlinux*)
+              pacman -Sy --noconfirm gcc openmpi
+              ;;
+            *)
+              echo "Unsupported distribution: ${{ matrix.distro }}"
+              exit 1
+              ;;
+          esac
+      - name: Download wheels artifact
+        uses: actions/download-artifact@v4
+        with:
+          merge-multiple: true
+          path: ./wheelhouse/
+      - name: Install wheel
+        # Install the appropriate file for vmecpp from the wheelhouse directory.
+        # --no-index prevents installing from PyPi, so we don't accidentally install
+        # a published version instead of the newly built ones. At the same time it prevents
+        # loading dependencies from PyPi, so the first installation fails. We only use the console output
+        # from this command to get the appropriate .whl file for this platform and environment.
+        run: |
+          ls wheelhouse/
+
+          . venv/bin/activate
+          wheel_filename=$(find wheelhouse/$(python --version | awk '{print $2}' | awk -F. '{printf "vmecpp*-cp%s%s-*manylinux*.whl", $1, $2}'))
+          echo "Found matching wheel: $wheel_filename"
+          if [ ${{ matrix.test-mpi }} = true ]; then
+            # Fedora linux needs to source openmpi in every new shell
+            if [[ ${{ matrix.distro }} = fedora* ]]; then
+              . /etc/profile.d/modules.sh
+              module load mpi/openmpi-x86_64
+            fi
+
+            pip install mpi4py
+          fi
+          pip install $wheel_filename
+
+          pip install pytest
+          python -m pytest tests/
+
+
   pypi-publish:
     name: Publish wheels to PyPI
     if: github.event_name == 'release'
-    needs: [main, make-sdist]
+    needs: [main, make-sdist, test-on-different-distros]
     runs-on: ubuntu-24.04
     environment:
         name: pypi
@@ -71,7 +169,7 @@ jobs:
     steps:
       - uses: actions/download-artifact@v4
         with:
-          path: wheelhouse
+          path: dist/
           merge-multiple: true
 
       - name: Publish package distributions to PyPI
